name: budgetr
description: An app to track your expenses
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  file_picker: ^4.1.4
  http: ^0.13.5
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  google_fonts: ^4.0.4
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.4.0
  logger: ^1.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon.png"

flutter:
  generate: true
  uses-material-design: true
  fonts:
  - family: Ubuntu
    fonts:
      - asset: fonts/Ubuntu-Regular.ttf
  assets:
    - assets/
    - assets/flags/
